
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";
import { Provider } from 'react-redux';
import store from '../redux/store';
import ClientComponent from '../../components/ClientComponent/ClientComponent';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return  (
    <html lang='eng'>
      <body>
      <Header />
      <ClientComponent>{children}</ClientComponent>
      <Footer />
      </body>
      </html>
  );
}
